export class SettingKeys {
  static FIRST_LAUNCH_VERSION : string = "FIRST_LAUNCH_VERSION";
  static THEME_MODE: string = "THEME";
  static LANGUAGE: string = "LANGUAGE";
  static GLOBAL_STATUS_FRESH_INTERVAL: string = "GSFI";
  static TASK_STATUS_FRESH_INTERVAL: string = "TSFI";
  static APP_VERSION_CODE: string = "APP_VERSION_CODE";
}

export class Aria2Keys {
  static DEFAULT: string = "DEFAULT_ARIA2";
  static ARIA2S: string = "ARIA2S"
}
